### ISSUE TITLE
Decouple project statistics popup from its constituents

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1194]
Currently, in `project-statistics-popup-helpers.ts` we define the following constants:

```
export const SOURCE_TOTAL = 'Total';
export const LICENSE_TOTAL = 'Total';
```
These couple these helpers to `AttributionCountPerSourcePerLicenseTable.tsx` and `CriticalLicensesTable.tsx`.

To reduce technical debt this coupling should be removed.

**Comment by someshkhandelia** [comment]
- I would also draw attention to the fact that `ProjectLicensesTable` is the generic table which is already decoupled from data logic of the statistic helper. 
- The tables `AttributionCountPerSourcePerLicenseTable` and `CriticalLicensesTable` are specific to statistics popup and therefore don't seem to have the need to be decoupled.  
- `ProjectLicensesTable` was decoupled (made generic) because it was reused across `AttributionCountPerSourcePerLicenseTable` and `CriticalLicensesTable`, but the latter two tables are used in the popup only and won't be reused with other data in future as well. If other data is used in future, it would be used directly with `ProjectLicensesTable`.
- Also reiterating a convention policy: "Don't make something too generic until it is used 3 times". `AttributionCountPerSourcePerLicenseTable` and `CriticalLicensesTable` are not used more than 1 time, and even if they are reused in future > 1 time, they will be used with the same data.

**Comment by benedikt-richter** [comment]
The main motivation of this ticket is to remove the coupling by "magic" keys in the data structure consumed by the two tables in question. 

In particular, the following interface causes this issue:

```
export interface AttributionCountPerSourcePerLicense {
  [licenseNameOrTotal: string]: { [sourceNameOrTotal: string]: number };
}
```

We use the constants to memorize the keys we want to treat differently. Instead the data structure should be more complex to explicitly handle the data for total values and therefore the "magic" constants are not needed anymore.
