### ISSUE TITLE
Make URLs in Report view clickable

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1222]
Currently URLs in Report view are simple strings. It would be nice to make them hyperlinks.

**Comment by someshkhandelia** [comment]
After verbal discussion with @vasily-pozdnyakov it was decided that we want to convert the text in the URL column in the Report View into a hyperlink. It will behave similar to the links in Audit and Attribution view i.e. the correctness of the link is left to be verified by the browser and not our application. 
![image](https://user-images.githubusercontent.com/9270691/207876387-2523f8a3-25a2-4551-b889-c80aee09a7be.png)

A second suggested alternative (if the first option didn't work for some reason) was to create a button to open URL instead of converting the text to a hyperlink.
![image](https://user-images.githubusercontent.com/9270691/207876604-2ca91997-0ffb-4d5f-81c7-56e54b3d6c3b.png)
