### ISSUE TITLE
Popups do not use the width correctly on high pixel count screens

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1244]
Their width is set at about 1500px, which does not scale at all with the screen resolution.

**Comment by mstykow** [comment]
If I understand this description correctly, you are unsure why popups stop growing past 1500px.
This is expected behavior. A popup that stretches over the entire width is usually undesired. But if it is, MUI offers the `fullWidth` prop on the `Dialog` component for this purpose. I don't think we have a problem though.
