### ISSUE TITLE
Fix icons for folder leaves in resource tree

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#1317]
Currently, the icons for folder leaves in resource tree are clickable and change after click (see screenshot):
![Screenshot 2023-01-12 at 12 50 48](https://user-images.githubusercontent.com/46576389/212059580-c337ed3f-89ff-4abe-ac8f-5f083f015172.png)

Instead the icons of folders that are leaves of the tree should be non-clickable, as clicking has no impact other than changing the icon what is confusing.

**Comment by someshkhandelia** [comment]
How to reproduce this bug?

1. Load "opossum_ui_scan_input.json.gz" file in the application
2. Click a signal "+" e.g. MIT to make it an atttribution
![image](https://user-images.githubusercontent.com/9270691/216002972-977df3c3-2bf2-4ecf-af5a-a94f1f133a83.png)
3. Click 'show resources' button on the attribution
![image](https://user-images.githubusercontent.com/9270691/216003540-d8ce44a4-b778-4862-b79d-adbc068372f0.png)
4. The resource tree that opens, should not have the highlighted icon clickable (currently it does, and that is the bug), because it is a leaf of the tree and clicking the icon doesn't do anything.
![image](https://user-images.githubusercontent.com/9270691/216004085-a9ea9cd3-8886-4800-91a8-5cb047b1a7cd.png)
