### ISSUE TITLE
Check and improve performance of file opening

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1481]
## Context

Currently, it takes quite a lot of time to open a file, especially big files.

## Idea

Check opening performance in profiler and find some ideas to improve it.

**Comment by benedikt-richter** [comment]
Please, elaborate a bit more on "prepopulate the output file". Does this mean OpossumUI does some prepopulation? If not this is probably not a fix here in the scope of OpossumUI.

**Comment by mstykow** [comment]
The issue is that we're loading too much data into the frontend. Imagine if our frontend were a real website: would you load 800MB of data from the backend before the user can start to interact with the UI?

So this is really an architectural problem. To fix it, we'd have to move a lot of calculations into the backend and then only expose chunks/streams of data to the frontend.

**Comment by mstykow** [comment]
Also related to #2460 (see my explanation there).
