### ISSUE TITLE
Check and improve saving

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#1482]
## Context

Currently, saving might take some time. A detailed profiling might help to find slow processes. Based on that different ways to improve performance can be discussed.

**Comment by benedikt-richter** [comment]
Would be great to detail a bit more. Which aspect do we want to improve? I guess this issue is about performance improvements?

In this case first there should be a detailed profiling and then the slow processes should be identified. After that is done we should identify the fix. Not sure we want to save async.

**Comment by benedikt-richter** [comment]
superceded by #1919
