### ISSUE TITLE
Replace web workers with node child processes

### ISSUE THREAD

**Issue by leslielazzarino** [opossum-tool/OpossumUI#1593]
This would allow us to move the multi-threading to the backend, saving memory in the V8 4GB VM. It should first be tried with one of the webworkers and optimized performance-wise.

Documentation: https://nodejs.org/api/child_process.html

**Comment by mstykow** [comment]
There is no advantage performance-wise to just using browser web workers. The serialization/deserialization still needs to be performed and we don't have a memory problem with our web workers anymore.

Besides, there is no need for a child process here because the electron app's main process and the renderer process _are already distinct_. See [here](https://www.electronjs.org/docs/latest/tutorial/process-model#window-management). So simply letting the main process handle the task would already be equivalent to the renderer process sending the job to a web worker.
