### ISSUE TITLE
Improve performance when saving large files

### ISSUE THREAD

**Issue by MarkusObendrauf** [opossum-tool/OpossumUI#1919]
Currently, saving large files takes a few seconds. I attempted to track down which operations are expensive on a 250mb (uncompressed size) project:

1. Copying/moving data from frontend to backend: 1.52 seconds. This was measured by printing the timestamp before [window.electronAPI.saveFile is called](https://github.com/opossum-tool/OpossumUI/blob/main/src/Frontend/state/actions/resource-actions/save-actions.ts#L194) and another timestamp after entering the [save file listener callback](https://github.com/opossum-tool/OpossumUI/blob/main/src/ElectronBackend/main/listeners.ts#L69)
2. [JSON.stringify(outputfileData)](https://github.com/opossum-tool/OpossumUI/blob/main/src/ElectronBackend/output/writeJsonToOpossumFile.ts#L23): 0.51 seconds
3. [Zipping the file](https://github.com/opossum-tool/OpossumUI/blob/main/src/ElectronBackend/output/writeJsonToOpossumFile.ts#L26): 1.10 seconds sync + 2.26 seconds async. Even though zipping is done async on a worker thread, we first need to copy all data to the worker. I believe this copying operation blocks the main thread for 1.1 seconds.

The code I used for timing can be found on this [branch](https://github.com/opossum-tool/OpossumUI/compare/main...MarkusObendrauf:OpossumUI:benchmark-copy)

## Possible Solutions Comparison
The speed can be imroved both in the code before the zipping and/or in the zipping itself.
#### Send Diff to BE instead of whole manualAttributions + ...
Effects on speed: 1.52s from 1. before should become <<1s, state change speed should become neglectably slower, same for BE before zipping
Code changes: collect state changes done when saving in a new format, appy changes from it in the BE

#### Do state changes on save in the BE
The part of the state needed for the output file is also stored in the BE. It is modified there and then sent to the FE to update the state. The copy operation would the happen while the zipping is in progress, not before
Effects on speed: 1.52s from 1. before happens in parallel to 2.26s in 3.
Code change: move save logic to BE, add a FE save listener similar to the current BE one

#### Do state changes on save in FE and BE
No copy operation needed, as both sides compute their own results.
Effects on speed: 1.52s from 1. before disappears
Code changes: save logic is shared between FE and BE

#### Send output data from FE to BE as string
This reduces the size of the copied object send, but splits the saving to file code between FE and BE
Effects on speed: 1.52s from 1. before becomes much smaller, possibly by a factor 2 to 4

#### Use a library that does not re-zip the input file 
see https://github.com/opossum-tool/OpossumUI/issues/1893
Effects on speed: unclear without testing, the improvement might be about 2s from 3. before, or might be slim to none if the new library is much slower than the old one
Code changes: replace zipping code in BE

#### Do not zip output syncronously
Possible strategy: 
a. create output file in a temporary folder un the main process, uncompressed
b. a child process in the BE watches for new files in this folder, when a new one is there it creates a new .opossum file
Effects on speed: 3. before goes down to <<1s
Code changes: add node child process and move zipping to it and add watcher logic to it.

#### Do operations in the BE in a child, non-blocking thread

**Comment by leslielazzarino** [comment]
Another possible idea: keep the part of the state necessary to write the output file also in the BE, in a child thread. When saving, the action input is also sent to the BE, causing the same changes in the child thread that are then written to a file without sending copies around.

**Comment by leslielazzarino** [comment]
For the possible other library, see https://github.com/opossum-tool/OpossumUI/issues/1893

**Comment by maxhbr** [comment]
The above solutions in table form:

| strategy  | 1. Copying/moving data from frontend to backend: 1.52 seconds. | 2. JSON.stringify(outputfileData): 0.51 seconds | 3. Zipping the file: 1.10 seconds sync + 2.26 seconds async.
| ------------- | ------------- | ------------- | ------------- |
| Send Diff to BE instead of whole manualAttributions + ... |  <<1s  |
| Do state changes on save in the BE | in parallel to 3  |
| Do state changes on save in FE and BE | 0 |
| Send output data from FE to BE as string | before becomes much smaller, possibly by a factor 2 to 4 |
| ------------- | ------------- | ------------- | ------------- |
| Use a library that does not re-zip the input file | | | might be about 2s from 3. before, might be slim to none |
| Do not zip output syncronously | | | <<1s |

**Comment by maxhbr** [comment]
If changes are followed in BE and FE, how is consistency guaranteed? Are all these requests happening in a synchronous thread and is the ordering guaranteed?

**Comment by leslielazzarino** [comment]
Best solutions for reducing the time before creating the file are: diff and double calculation

**Comment by mstykow** [comment]
The performance in the main thread is acceptable, especially because it does not actually block the renderer process.
The issue with slow performance, i.e. blocks in the renderer process is because of the vast amount of data (sometimes multiple GB) that the UI needs to handle. Expensive calculations that belong into the main thread are performed by the renderer thread.

None of the suggestions of this task will fix this issue.
