### ISSUE TITLE
Incorrect data in "critical signals" pie chart in statistics popup

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#2146]
**Context**

It seems that there is some discrepancy between the number of highly critical licenses shown in the "Critical Signals" piechart in Statistics Popup and in the “Criticality Bar” shown in the top bar.

**How to reproduce**

* Open `output_opossum.json` example file
* checkout the number of highly critical signals in the "Critical Signals" piechart in the Statistics Popup (0)
* navigate to audit view and switch to the criticality bar
* checkout the number of highly critical signals in the criticality bar (311)

In this example it can be seen that there are no highly critical signals in the piechart while there are highly critical signals in the criticality bar:

![Screenshot 2023-10-11 at 18 12 51](https://github.com/opossum-tool/OpossumUI/assets/46576389/1332e1d8-607f-4291-847d-5b8dd7188268)
![Screenshot 2023-10-11 at 18 13 54](https://github.com/opossum-tool/OpossumUI/assets/46576389/d65256a5-fbc3-40bb-b5ec-5132406f4ee7)

**Definition of Done**

The cause for this difference is identified and if necessary fixed.

**Comment by vasily-pozdnyakov** [comment]
Decided to do: 
*Merged signals should be counted as one item at the project statistics popup
*Use "Signals Count" instead of "Count"
*Rename "Critical signals" to "Signals by criticality"
*Modify the heuristics to take the highest criticality at the statistics when there are license variants with different criticalities (here we take the risk of false-critical signals). At the end, colors at the "Critical signals" pie chart should agree with colors at Criticality Progress bar
