### ISSUE TITLE
Introduce ranking of suggestions

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#2345]
Rank the suggestions using the following list of criteria
* is pre-selected
* grey star
* remaining suggestions by priority of the source of the respective signal

Note that attributions should for now be ignored for suggestions. In the future these might be taken into account. Ones with golden stars might play a special role.

**Comment by mstykow** [comment]
I won't do the "pre-selected" attribute for now as I'm not sure how much value it really adds since most suggestions come from signals which can never be pre-selected. On the other hand, we could rank signals there were pre-selected somewhere in the folder content higher. Just not sure if this would rather confuse than help since a resource's child may not be directly related to its parent.
