### ISSUE TITLE
Add table showing critical licenses

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#947]
Add a table showing critical licenses (clustered by criticality high or medium).  The table should have two columns: One should contain the license name and the other one total number. 
Make sure to use deduplicated data as described in #943.

**Comment by someshkhandelia** [comment]
Currently the statistics popup looks like this:
![image](https://user-images.githubusercontent.com/9270691/191931782-3f5719bc-73b3-4395-b52d-ce42344e733e.png)
After a verbal discussion with @vasily-pozdnyakov and @Billwuzl, it was understood that the goal of this issue is to essentially extract a table, out of the **Signals per Sources** table, that contains the **high** (red) and **medium** (orange) critical license names and their **total** numbers.

**Comment by benedikt-richter** [comment]
Exactly, this would be the goal. In the long run one could also image to merge both tables into a more complex one with sorting and filtering. However, for the moment a new one like the one you describe would be nice.
