### ISSUE TITLE
Enable keyboard navigation in package lists

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#971]
**Is your feature request related to a problem? Please describe.**
Currently, navigating the package lists, a user has to click each package individually in order to traverse the list.
For the user that implies the need to click a lot.

Navigation:
- simple up-down navigation with arrows
- experiment if it's better to select the item with space or if an item should be immediately selected after the navigation event

**Describe the solution you'd like**
As a user navigating a package list, I want to be able to use keyboard navigation.

**Comment by someshkhandelia** [comment]
As per verbal discussion, it is assumed that the user first clicks (selects) atleast one item in the given tree / list and then there is the possibility to navigate using keyboard.

**Comment by someshkhandelia** [comment]
So far, could find two ways to do this:
1. Revamp entire architecture and use an actual Tree instead of a VirtualizedList, https://mui.com/material-ui/react-tree-view/
2. Create a custom hook for keyboard input for the existing VirtualizedList, https://whereisthemouse.com/create-a-list-component-with-keyboard-navigation-in-react

**Comment by mstykow** [comment]
As of #2208 we can implement this feature pretty directly by following these instructions: https://virtuoso.dev/keyboard-navigation/
