### ISSUE TITLE
Hide signals of attributed resources in "signals in folder content" panel

### ISSUE THREAD

**Issue by vasily-pozdnyakov** [opossum-tool/OpossumUI#982]
**Is your feature request related to a problem? Please describe.**
Currently, as a user, I see all the signals attached to resources contained in a folder in the "signals in folder content" panel. However, I,m only interested in signals, that are attached to resources which do not have attribution attached (since these are "unresolved").
Such signals are not of interest, as an attribution that is attached to a resource propagates down and also applies to all its children (until there is another attribution attached to a child). In consequence, the signals are no longer relevant for all resources higher in the resource tree, as there is already an attribution.

**Describe the solution you'd like**
Therefore, these signals should be hidden in "signals in folder content" panel.

**Comment by benedikt-richter** [comment]
This seems to be a helpful feature. However, not sure how much it would really impact the user's experience.

**Comment by mstykow** [comment]
I'm not sure I'm convinced by the arguments here. After all, what if I want to analyze signals in the folder content even if attributions have been made. For example, in order to see any critical signals regardless of whether has an attribution has been made or not.
What's being described here is quite similar to the hide/unhide signals feature we already have. We could consider auto-hiding signals that belong to resources on which attributions have been made. Then, the user can use the visibility toggle button to reveal the hidden signals again.
For the time being, I am not aware of there being an issue with the current situation and I'm thus closing this task until further notice.
