### ISSUE TITLE
In audit view signals are not sorted by number of occurrences

### ISSUE THREAD

**Issue by benedikt-richter** [opossum-tool/OpossumUI#989]
In the past we sorted signals in audit view by the number of occurrences. 

This is no longer the case:
![Screenshot 2022-09-15 at 08 31 27](https://user-images.githubusercontent.com/46576389/190331597-4b3f8bad-4c3a-4f05-a240-f73fee7c9457.png)

This feature should be restored.

**Comment by someshkhandelia** [comment]
From analysis of Windows .exe releases [here](https://github.com/opossum-tool/OpossumUI/releases):

it was found that [20220803](https://github.com/opossum-tool/OpossumUI/releases/tag/OpossumUI-2022-08-03) release works and entries are sorted, but [20220817](https://github.com/opossum-tool/OpossumUI/releases/tag/OpossumUI-2022-08-17) release does not work and the entries are not sorted there.

The 20220817 release is just after the 20220803 release, and therefore we can assume that changes made here must have lead to somehow break the sorting.

**Comment by someshkhandelia** [comment]
Some useful git stuff:

- Find a commit with particular commit message: [Link](https://stackoverflow.com/questions/7124914/how-to-search-a-git-repository-by-commit-message)
- How to reset/revert a file to a specific commit: [Link](https://stackoverflow.com/questions/215718/how-do-i-reset-or-revert-a-file-to-a-specific-revision)

**Comment by someshkhandelia** [comment]
The changes made by the [commit](https://github.com/opossum-tool/OpossumUI/commit/94f7c52eedc30244c78219e41bb22b50a90d8fda) to the [component](https://github.com/opossum-tool/OpossumUI/blame/8d56f52ce6b9a2f6ca916f4018b1dd985fc49bd0/src/Frontend/Components/ResourceDetailsTabs/ResourceDetailsTabs.tsx) were reverted, and we tested if sorting is fixed. However, sorting is still not fixed. Thus, it can be concluded that the changes made to this particular component by the commit did not introduce the bug.

However, we will now try to completely revert the commit in question (and not just the changes in particular components) and see if the commit itself somehow introduced the bug (via some indirect changes).

**Comment by someshkhandelia** [comment]
Resetting the repository to the following commit, resolves the bug:


![Image](https://user-images.githubusercontent.com/9270691/190992159-d62d8892-f48f-4cd9-9d90-5009ea6a96b3.png)

Basically, the above commit is 1 commit before the [commit](https://github.com/opossum-tool/OpossumUI/commit/94f7c52eedc30244c78219e41bb22b50a90d8fda) we have been interested in.

To further confirm that [commit](https://github.com/opossum-tool/OpossumUI/commit/94f7c52eedc30244c78219e41bb22b50a90d8fda) may have caused the issue, we will now try to just **revert** that particular commit instead of **resetting** the entire repository to before that commit.

**Comment by someshkhandelia** [comment]
Reverting the [commit](https://github.com/opossum-tool/OpossumUI/commit/94f7c52eedc30244c78219e41bb22b50a90d8fda) of interest (see image below), is leading to merge conflicts, following which the OpossumUI application cannot be tested, since it doesn't start because of merge conflict markers in code. We need to resolve this conflict to proceed.



![Image](https://user-images.githubusercontent.com/9270691/190995806-2eb63145-f06f-496f-b784-736c7a122ac3.png)

**Comment by someshkhandelia** [comment]
Resolving merge conflicts from https://github.com/opossum-tool/OpossumUI/issues/989#issuecomment-1250829555 proved difficult and so we took another approach.

Resetting the repository to the following commit, still has the bug:


![Image](https://user-images.githubusercontent.com/9270691/191022255-8eda632d-549f-4168-aa98-1b9ac836b205.png)

However, from https://github.com/opossum-tool/OpossumUI/issues/989#issuecomment-1250809316 we know that resetting to a commit just before the commit in the image above makes our application free of this bug. **Therefore, it can be firmly concluded that  [commit](https://github.com/opossum-tool/OpossumUI/commit/94f7c52eedc30244c78219e41bb22b50a90d8fda) has introduced the bug.**

**Comment by someshkhandelia** [comment]
Verbal discussion: Probably we are alphabetically re-sorting the already sorted attributions that are coming from the workers, leading to this bug at hand.
